### ISSUE TITLE
Animate by HTML element

### ISSUE THREAD

**Issue by robotzero1** [KevinBatdorf/animate-in-view#17]
Thanks for the plugin. 

Just a question really. I started adding it according to the docs but because the client has every section on the page animating it started to get complicated so I thought of an alternative way for me to do this. I've change the code in the plugin (I know this will get wiped on updates) to this:

```
document.querySelectorAll('.animatein :is(h1, h2, h3, p, img, .wp-block-buttons').forEach(function (el) {

    const threshold = 0.5;
    el.style.opacity = 0;
    const once = 1;
	
    const observer = new IntersectionObserver(function (entries) {
        if (entries[0].intersectionRatio === 0) {
            el.classList.remove(el.getAttribute('animatein'));
            return;
        }
        if (entries[0].intersectionRatio < Number(threshold)) {
            return;
        }
        el.classList.add('animate-in-view');
        Number(once) && observer.unobserve(el);
    }, { threshold: [Number(threshold), 0] });
    observer.observe(el);
});
```
So now I just add 'animatein' to the Additional CSS classes for the each row I want the contents to animate. It seems to work fine but I wondered if you saw any problems with this approach?

**Comment by KevinBatdorf** [comment]
It seems fine, but do you need the plugin at all then at this point? Seems like you can just put that code into your own file and it will work how you want. You just need the CSS as well for the transition.

https://github.com/KevinBatdorf/animate-in-view/blob/main/src/front/style.css

**Comment by KevinBatdorf** [comment]
Will close but let me know if you need anything else. Happy to help
